### ISSUE TITLE
Will the project bring i18n back in somedays?

### ISSUE THREAD

**Issue by qilin102223** [lyc8503/onedrive-cf-index-ng#18]
as the title.

**Comment by lyc8503** [comment]
There should be no plans for this in the near future. Apart from the initial setup screen, all the ui's are just some short English words, and there are nice icons as well, so it shouldn't affect most people's usage (those who don't speak English can easily “guess out” how to use it).

The i18n was removed because it had poor support for edge computing environments at the time, and also because I didn't have much incentive to maintain translations in multiple languages.

**Comment by qilin102223** [comment]
Got it, thank you so much.
