### ISSUE TITLE
Please help me fix the error | Nhờ thím trợ giúp sửa lỗi

### ISSUE THREAD

**Issue by thangbeta** [lyc8503/onedrive-cf-index-ng#26]
![loi 2](https://github.com/user-attachments/assets/c1332579-c682-4249-bf9b-143e2379c561)
 Mình làm theo các bước hướng dẫn thì báo lỗi ntn, nhờ thím hướng dẫn cách sửa với nha. Cảm ơn thím
---
*Translation: I followed the instructions and got this error. Please show me how to fix it. Thank you.*

**Comment by lyc8503** [comment]
Hi, I can only speak English or Chinese, so please translate your comments to English first.

Could you please post the error message in `F12` DevTools or give me a link to your deployed instance?

**Comment by thangbeta** [comment]
Tks you reply. My page link
https://onedrive-cf-index-ng-79r.pages.dev/

**Comment by lyc8503** [comment]
Hi, could you try upgrading to the latest version and try again? You can re-fork the repository and deploy it again.  If the problem persists, please provide a screenshot of the error message in DevTools.

**Comment by lyc8503** [comment]
> thanks for making this awesome project bro. I want learn How can I change my onedrive index site name made in workers? not domain....only site name in URL
> 
> and one more thing, u said I can add Microsoft email on variables also, so what will be the environment variable name? for now I added on github config

IIRC, you can't rename your current project, you may have to delete and recreate it with the name you want from the beginning (the project name will be your subdomain prefix). The variable name is `USER_PRINCIPLE_NAME` as shown in the config file, you can add that at Cloudflare Dashboard. BTW, please open a new issue instead of asking in an unrelated one if you still have questions.

**Comment by spidy2356** [comment]
Thank u so much sir
