### ISSUE TITLE
Support numerical order

### ISSUE THREAD

**Issue by arm64x** [lyc8503/onedrive-cf-index-ng#31]
Hello, can you support with sorting files by numerical order?

For example: 01, 02...09,10,11...99,100,101

Currently it is sorting by lexicographical order: 01, 02...09,10,100,101...109,11,110

Thank

**Comment by lyc8503** [comment]
This can be difficult, as the current implementation returns the contents of the folder in a paged fashion, and the order in which they are returned is determined by Microsoft's API: https://learn.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_list_children

and this API does not support sorting by numerical order: https://learn.microsoft.com/en-us/onedrive/developer/rest-api/concepts/optional-query-parameters

Maybe for now you have to prepopulate the zeroes so that the lexicographical order matches the numerical order, something like: `0001,0002,... ,0010,... ,0100,... `
