### ISSUE TITLE
is translation possible? 

### ISSUE THREAD

**Issue by wellingto198** [lyc8503/onedrive-cf-index-ng#32]
I wanted to translate it into my language, but I couldn't find where the texts are... 
I'm just curious, I don't know almost anything, my maximum is html and css

**Comment by lyc8503** [comment]
Sorry, I removed the internationalization feature from this project due to compatibility issues with the Cloudflare platform.

I don't think there's very complex English in the project, and also I only know English and Chinese, and maintaining the language files could be a tedious task, so it's probably unlikely that internationalization will be reintroduced for a while.

If you want to be able to translate it, you need to manually modify the strings in all `tsx` files in the project.

In any case, thank you very much for your willingness to contribute to the project.
